Repository ablecloud-team/ablestack-cockpit-plugin, pull requests merged in 2021-03, with the labels that each got.

#63 클러스터 구성 준비 마법사 프로토타입 작업
  .DS_Store
  main.html
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
Labels: 클러스터 구성 준비(마법사)

#62 python 개발 sample과 common module 작성
  .gitignore
  python/SampleModule/__init__.py
  python/SampleModule/main.py
  tools/ablestack_common/LICENSE
  tools/ablestack_common/MANIFEST.in
  tools/ablestack_common/README.md
  tools/ablestack_common/ablestack/__init__.py
  tools/ablestack_common/ablestack/common/__init__.py
  tools/ablestack_common/ablestack/common/able_logger.py
  tools/ablestack_common/ablestack/common/able_return.py
  tools/ablestack_common/setup.cfg
  tools/ablestack_common/setup.py
Labels: Development

#67 디스크, 네트워크 정보조회 기능 개발
  python/__init__.py
  python/disk/README.md
  python/disk/__init__.py
  python/disk/disk_action.py
  python/nic/README.md
  python/nic/__init__.py
  python/nic/network_action.py
Labels: Development, 스토리지센터 VM 배포 마법사, 클라우드센터 VM 배포 마법사

#69 클라우드센터VM 마법사 UI 프로토타입 작성
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.html
Labels: 클라우드센터 VM 배포 마법사

#68 스토리지센터 가상머신을 위한 XML 생성 기능
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.html
Labels: 스토리지센터 VM 배포 마법사

#73 CentOS8 에서의 lspci 버그 수정
  python/disk/disk_action.py
Labels: 스토리지센터 VM 배포 마법사

#71 pcs 관련 기능 개발
  .vscode/settings.json
  python/pcs/__init__.py
  python/pcs/main.py
  python/pcs/pacemaker.py
Labels: 클라우드센터 VM 배포 마법사

#80 PCS 관련 README.md 파일 생성
  python/pcs/README.md
Labels: documentation

#88 PCS Cluster 삭제 기능 추가
  python/pcs/main.py
  python/pcs/pacemaker.py
Labels: 클라우드센터 VM 배포 마법사, 클라우드센터 가상머신 상태, 클라우드센터 클러스터 상태

#75 스토리지 및 클라우드 센터 관련 연결 주소 생성 기능
  python/url/README.md
  python/url/__init__.py
  python/url/create_address.py
Labels: 스토리지센터 가상머신 상태, 스토리지센터 클러스터 상태, 클라우드센터 가상머신 상태, 클라우드센터 클러스터 상태

#89 README.md 파일 업데이트
  python/pcs/README.md
Labels: 클라우드센터 VM 배포 마법사, 클라우드센터 클러스터 상태

#77 스토리지 클러스터 상태 조회 화면 개발 (Storage Cluster Status)
  main.html
  python/storage_center_cluster_status/readme.md
  python/storage_center_cluster_status/scc_status_detail.py
  python/storage_center_cluster_status/scc_status_update.py
  python/storage_center_vm_status/readme.md
  python/storage_center_vm_status/scvm_status_detail.py
  python/storage_center_vm_status/scvm_status_update.py
  src/features/main.js
  src/features/storage-cluster-maintenance-update.html
  src/features/storage-cluster-maintenance-update.js
  src/features/storage-vm-resource-update.html
  src/features/storage-vm-resource-update.js
  src/features/storage-vm-status-update.html
  src/features/storage-vm-status-update.js
Labels: 스토리지센터 가상머신 상태

#96 #86 cloudinit 기능 개발 브렌치입니다.
  tools/cloudinit/build.sh
  tools/cloudinit/gencloudinit.py
  tools/cloudinit/meta-data.tmpl
Labels: 스토리지센터 VM 배포 마법사, 클라우드센터 VM 배포 마법사

#99 #100 cloudinit scvm의 cockpit service를 실행하는 명령추가
  tools/cloudinit/gencloudinit.py
Labels: 스토리지센터 VM 배포 마법사, 클라우드센터 VM 배포 마법사

#74 클라우드센터 클러스터 상태 UI
  main.html
  python/card-cloud-cluster-status.py
  src/.DS_Store
  src/features/card-cloud-cluster-status.js
  src/features/main.js
Labels: 클라우드센터 클러스터 상태

#93 클러스터 구성 준비 마법사 UI 개발
  src/common/validation.js
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
  src/features/storage-vm-wizard.html
Labels: 클러스터 구성 준비(마법사)

#91 PCS 클러스터, 리소스 삭제 및 상태 조회 예외 처리 코드 추가
  python/pcs/README.md
  python/pcs/__pycache__/pacemaker.cpython-36.pyc
  python/pcs/pacemaker.py
Labels: 클라우드센터 클러스터 상태

#103 스토리지센터 가상머신 nic명(enp0s20, enp0s21, enp0s22) 수정반영
  .gitignore
  .vscode/settings.json
  python/storage_center_vm_status/scvm_status_detail.py
Labels: 스토리지센터 VM 배포 마법사

#104 Storage vm wizard UI 기능 개발
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_ccvm_xml.py
  python/vm/create_scvm_cloudinit.py
  python/vm/create_scvm_xml.py
  python/vm/host_ping_test.py
  python/vm/reset_cloud_center.py
  python/vm/reset_storage_center.py
  python/vm/setup_pcs_cluster.py
  python/vm/setup_storage_vm.py
  src/common/wizard-common.js
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/storage-vm-wizard.html
  src/features/storage-vm-wizard.js
  tools/xml-template/ccvm-xml-template.xml
  tools/xml-template/ccvm.xml
  tools/xml-template/scvm-xml-template.xml
Labels: 스토리지센터 VM 배포 마법사
