Repository ablecloud-team/ablestack-cockpit-plugin, pull requests merged in 2021-04, with the labels that each got.

#111 클러스터 준비 마법사 SSH Key 파일명 변경
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
Labels: bug

#108 리본요약UI 및 연결주소 생성 관련 버그 수정
  main.html
  python/url/create_address.py
  src/features/main.js
Labels: bug

#112 #110 스크립트 경로 변경
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_scvm_cloudinit.py
  python/vm/reset_cloud_center.py
  python/vm/setup_pcs_cluster.py
  src/features/cloud-center-virtual-machine.js
  src/features/cloud-vm-wizard.js
  src/features/main.js
  src/features/storage-vm-wizard.js
  tools/ablestack_common/ablestack/__init__.py
Labels: bug, enhancement

#121 hosts 파일 정보를 세션스토리지에 저장
  src/features/main.js
Labels: enhancement

#140 요약리본UI 및 호스트 추가액션 후 페이지 접근 시 상태조회 오류
  main.html
  src/features/main.js
Labels: bug

#146 ablestack-cockpit-plugin rpm 생성
  tools/makerpm/README.md
  tools/makerpm/ablestack.sh
  tools/makerpm/ablestack.spec
  tools/makerpm/rpmbuild.sh
Labels: enhancement

#116 SCVM, SCC 상태 조회(default값 고정, nic 조회 방식 변경)
  main.html
  python/scc_status/readme.md
  python/scc_status/scc_status_detail.py
  python/scc_status/scc_status_update.py
  python/scvm_status/readme.md
  python/scvm_status/scvm_status_detail.py
  python/scvm_status/scvm_status_update.py
  python/storage_center_vm_status/scvm_status_detail.py
  src/features/cloud-center-virtual-machine.js
  src/features/main.js
  src/features/storage-cluster-maintenance-update.js
  src/features/storage-vm-resource-update.js
  src/features/storage-vm-status-update.html
  src/features/storage-vm-status-update.js
Labels: bug

#152 SCVM 상태 조회시 관리 NIC GW정보 조회 기능 추가(ssh scvm이용하여 gw정보 조회 가능확인)
  main.html
  python/scc_status/readme.md
  python/scc_status/scc_status_detail.py
  python/scc_status/scc_status_update.py
  python/scvm_status/readme.md
  python/scvm_status/scvm_status_detail.py
Labels: bug

#151 클라우드 센터 화면 문구 수정
  main.html
  python/cloud_cluster_status/card-cloud-cluster-status.py
  python/host/virshlist.py
  src/common/wizard-common.js
  src/features/card-cloud-cluster-status.js
  src/features/cloud-center-virtual-machine.js
  src/features/storage-vm-wizard.js
Labels: enhancement

#123 클러스터 준비 마법사 SSH Key, hosts파일 기능 개선 및 UI 버그 수정
  src/common/validation.js
  src/common/wizard-common.js
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
Labels: bug

#148 스토리지센터 연결 오류
  python/url/create_address.py
  src/features/main.js
Labels: bug

#154 scvm 서버용, 복제용 NIC Type 값(NIC passthrough) 조회방식 변경
  main.html
  python/scc_status/scc_status_detail.py
  python/scvm_status/scvm_status_detail.py
  src/features/main.js
Labels: enhancement

#149 #135 scvm 자동 bootstrap 파일 작성
  shell/host/bootstrap.sh
  tools/ablestack_common/ablestack/__init__.py
  tools/cloudinit/gencloudinit.py
Labels: enhancement

#156 ablecloud plugin 클라우드 센터 카드부분 문구 수정 및 다른 서버에 있는 ccvm disk 정보 조회
  python/host/virshlist.py
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_ccvm_xml.py
  python/vm/create_scvm_xml.py
  python/vm/setup_pcs_cluster.py
  python/vm/setup_storage_vm.py
  src/features/cloud-center-virtual-machine.js
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.js
  src/features/storage-vm-wizard.js
  tools/xml-template/ccvm-xml-template.xml
  tools/xml-template/scvm-xml-template.xml
Labels: enhancement

#161 요약리본 UI 배포상태 알림메세지 오류
  src/features/main.js
Labels: bug

#158 클러스터 준비 및 스토리지 센터 VM배포 마법사에서 UI 버그 수정
  src/features/cluster-config-prepare.js
  src/features/storage-vm-wizard.html
Labels: bug

#163 @kt-cheon NIC가 connecting 상태일 때 잘못된 값을 파싱하는 버그 수정
  python/nic/network_action.py
  tools/makerpm/README.md
Labels: bug

#166 scvm 및 ccvm 2차 테스트 개선사항 수정
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_ccvm_xml.py
  python/vm/create_scvm_cloudinit.py
  python/vm/create_scvm_xml.py
  python/vm/reset_cloud_center.py
  python/vm/reset_storage_center.py
  python/vm/setup_pcs_cluster.py
  python/vm/setup_storage_vm.py
  src/common/wizard-common.js
  src/features/cloud-vm-wizard.js
  src/features/storage-vm-wizard.html
  src/features/storage-vm-wizard.js
  tools/xml-template/scvm-xml-template.xml
Labels: enhancement

#177 #167 cockpit 메뉴 순서 변경
  manifest.json
Labels: enhancement

#179 scvm 삭제시 리턴 값 수정/ 30초마다 화면 갱신기능 반영
  main.html
  python/scvm_status/scvm_status_detail.py
  python/scvm_status/scvm_status_update.py
  src/features/main.js
Labels: enhancement

#182 3차 테스트 진행 개선사항 반영
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_scvm_xml.py
  python/vm/reset_cloud_center.py
  python/vm/reset_storage_center.py
  python/vm/setup_pcs_cluster.py
  src/common/wizard-common.js
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/storage-vm-wizard.html
  src/features/storage-vm-wizard.js
  tools/vmconfig/readme.md
  tools/xml-template/ccvm-xml-template.xml
  tools/xml-template/ccvm.xml
  tools/xml-template/scvm-xml-template.xml
  tools/xml-template/scvm.xml
Labels: enhancement

#178 공통 validation - IP/Cidr 포멧 형식 체크 버그 수정 및 wizard 네트워크 IP 관련 validation 추가 적용
  src/common/validation.js
Labels: enhancement

#183 #180 cloud center vm 조회 에러
  main.html
  python/host/virshlist.py
  src/features/card-cloud-cluster-status.js
  src/features/cloud-center-virtual-machine.js
  src/features/main.js
Labels: enhancement

#186 클라우드 센터 가상머신 상태 에러 메세지 수정
  src/features/cloud-center-virtual-machine.js
Labels: bug

#184 #174 plugin에서 ceph의 bootstrap명령어를 실행 시킬수 있는 기능 추가
  main.html
  shell/host/bootstrap_run.sh
  src/features/main.js
  src/features/storage-cluster-maintenance-update.js
  src/features/storage-vm-resource-update.js
  src/features/storage-vm-status-update.html
  src/features/storage-vm-status-update.js
Labels: enhancement

#190 #189 클라우드센터 클러스터 상태값(Health) 수정
  main.html
  src/features/card-cloud-cluster-status.js
  src/features/main.js
Labels: enhancement

#193 #188 ccvm의 부트스트랩 코드 생성입니다.
  shell/host/ccvm_bootstrap.sh
  shell/host/scvm_bootstrap.sh
  tools/cloudinit/gencloudinit.py
Labels: enhancement

#192 scvm 및 ccvm vmconfig 폴더권한 변경 및 xml 생성로직 수정
  python/vm/create_ccvm_xml.py
  python/vm/create_scvm_xml.py
  tools/xml-template/ccvm-xml-template.xml
  tools/xml-template/scvm-xml-template.xml
Labels: bug

#198 #196, #197 scvm bootstrap 관련 작업
  shell/host/scvm_bootstrap.sh
Labels: enhancement

#200 hosts파일 편집 시 "Tab 키" 사용에 관한 버그 수정
  src/features/cluster-config-prepare.js
Labels: bug

#208 요약 리본 UI - 부트스트랩 실행 상태 조회에 따른 알림메세지 추가, main.js 파일에 pluginpath 적용 및 에러처리 추가
  src/features/main.js
Labels: enhancement

#215 scvm 삭제시 /etc/ceph 하위 삭제, 30초 상태 조회시 sppiner 삽입 및 문구 수정
  main.html
  python/scvm_status/scvm_status_detail.py
  python/scvm_status/scvm_status_update.py
  src/features/card-cloud-cluster-status.js
  src/features/cloud-center-virtual-machine.js
  src/features/main.js
  src/features/storage-cluster-maintenance-update.js
  src/features/storage-vm-resource-update.js
  src/features/storage-vm-status-update.js
Labels: enhancement

#213 #210 호스트 키 스캔기능 개발
  python/host/ssh-scan.py
  shell/host/ccvm_bootstrap.sh
  shell/host/scvm_bootstrap.sh
  shell/host/ssh-scan.sh
Labels: enhancement

#216 클러스터 준비 마법사 - SSH Key 임시 파일 사용, 호스트 프로파일, 시간서버 단계에서의 기능 개선 및 버그 수정
  src/features/cluster-config-prepare.js
Labels: bug

#214 4차 테스트 scvm, ccvm 배포 마법사 기능 개선
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_scvm_cloudinit.py
  python/vm/host_ping_test.py
  python/vm/reset_cloud_center.py
  python/vm/setup_pcs_cluster.py
  python/vm/setup_storage_vm.py
  src/features/cloud-vm-wizard.js
  src/features/storage-vm-wizard.js
Labels: enhancement

#219 #209 bootstrap 조회 및 수정기능 개발
  python/ablestack_json/ablestackJson.py
  python/cloudinit_status/README.md
  python/cloudinit_status/cloudinit_status.py
  tools/properties/ablestack.json
Labels: enhancement

#222 scvm bootstarp 실행 여부 확인
  main.html
  python/scvm_status/scvm_status_detail.py
  python/scvm_status/scvm_status_update.py
  shell/host/scvm_bootstrap_run.sh
  src/features/cloud-center-virtual-machine.js
  src/features/main.js
  src/features/storage-cluster-maintenance-update.js
  src/features/storage-vm-resource-update.js
  src/features/storage-vm-status-update.js
Labels: enhancement

#223 scvm, ccvm bootstrap 실행여부에 따른 요약리본 UI 알림메세지 출력
  python/url/create_address.py
  src/features/main.js
Labels: enhancement

#224 클라우드센터 부트스트랩 실행기능 추가
  main.html
  shell/host/bootstrap_run.sh
  shell/host/scvm_bootstrap_run.sh
  src/features/card-cloud-cluster-status.js
  src/features/cloud-center-virtual-machine.js
  src/features/main.js
  src/features/storage-vm-status-update.js
Labels: enhancement

#233 스토리지 및 클라우드센터 가상머신 상태 관리 NIC 넷마스크 추가
  main.html
  python/scvm_status/scvm_status_detail.py
  src/features/cloud-center-virtual-machine.js
  src/features/main.js
Labels: enhancement

#234 클라우드센터 prefix 추가
  main.html
  python/host/virshlist.py
  src/features/cloud-center-virtual-machine.js
Labels: enhancement

#235 기능 개선 (키스캔, 부트스트랩 프로퍼티 초기화, 센터 연결시 알림메세지 모달표시)
  python/url/create_address.py
  src/features/card-cloud-cluster-status.js
  src/features/main.js
Labels: enhancement

#232 bootstrap 시 host추가기능 비활성화 문제 해결
  shell/host/scvm_bootstrap.sh
Labels: bug

#237 요약리본 UI - 상태조회 전 버튼 hide 처리
  src/features/main.js
Labels: bug

#239 클러스터 준비 마법사 - 시간서버 - 설정 값 변경
  src/features/cluster-config-prepare.js
Labels: bug

#241 클러스터 준비 마법사 - 시간서버 - 설정 값 변경 (추가 수정)
  src/features/cluster-config-prepare.js
Labels: bug

#243 ablestack 스토리지 가상머신 상태 NIC Type N/A 표기 버그 수정
  python/scvm_status/scvm_status_detail.py
Labels: bug

#245 스토리지센터vm 연결 시 url 링크 버그
  python/url/create_address.py
Labels: bug

#250 pcs 상태 조회 시 host의 online/offline 상태 추가
  python/pcs/pacemaker.py
Labels: bug

#253 #252 ipcorrector가 scvm의 crontab에 정상적으로 적용 안되는 문제 해결
  shell/host/ipcorrector
  shell/host/scvm_bootstrap.sh
  tools/cloudinit/gencloudinit.py
Labels: Development

#254 #252 잘못된 공백라인 수정
  shell/host/scvm_bootstrap.sh
Labels: bug

#257 스토리지 클러스터 상태(게이트웨이 상태 - 실행중 count추가) 수정
  src/features/main.js
Labels: enhancement
