Repository ablecloud-team/ablestack-cockpit-plugin, pull requests merged in 2021-11, with the labels that each got.

#318 오탈자 수정
  src/features/card-cloud-cluster-status.js
  src/features/cluster-config-prepare.html
Labels: bug

#316 클러스터 구성 준비 - Hosts 파일, 시간서버 단계 기능 개선
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
Labels: bug, enhancement

#321 클라우드센터vm 스냅샷 생성기능 및 클라우드센터 가상머신 배포 시 ccvm 스냅샷 생성 crontab 등록 기능 개발
  main.html
  python/ccvm_snap/ccvm_snap_action.py
  python/vm/setup_pcs_cluster.py
  src/features/card-cloud-cluster-status.js
  src/features/cloud-center-virtual-machine.js
Labels: enhancement

#323 1. skydive 주소생성 코드 삭제 2. skydive 명칭 변경에 따른 코드 수정
  python/url/create_address.py
  src/features/card-cloud-cluster-status.js
  src/features/wall-monitoring-wizard.js
Labels: enhancement

#319 CCVM, SCVM 배포마법사에서 개선된 호스트 파일 입력 기능 적용 및 클러스터 구성 준비 마법사에서 로컬시간서버 사용 제한 기능 추가
  manifest.json
  src/common/wizard-common.js
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
  src/features/storage-vm-wizard.html
  src/features/storage-vm-wizard.js
Labels: bug, enhancement

#324 클라우드센터 가상머신 live 상태에서 디스크 스냅샷 백업 가능하도록 기능 개선
  python/ccvm_snap/ccvm_snap_action.py
  python/ccvm_snap/create_ccvm_snap.py
  src/features/card-cloud-cluster-status.js
  src/features/cloud-center-virtual-machine.js
Labels: enhancement

#326 1. hosts파일 버그 수정 2. UI 버그 수정 3. 코드청소
  src/common/validation.js
  src/common/wizard-common.js
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.js
  src/features/storage-vm-wizard.js
Labels: bug

#327 cloudstack usage 자동 시작 변경
  shell/host/ccvm_bootstrap.sh
Labels: bug

#328 Update scvm_bootstrap.sh
  shell/host/scvm_bootstrap.sh
Labels: enhancement
