Repository ablecloud-team/ablestack-cockpit-plugin, pull requests merged in 2021-09, with the labels that each got.

#280 Wall 모니터링센터구성 상태리본 표기
  main.html
  src/common/wizard-common.js
  src/features/card-cloud-cluster-status.js
  src/features/main.js
Labels: enhancement

#283 podman 버전 업데이트에 따른 명령어 변경 적용
  shell/host/scvm_bootstrap.sh
Labels: bug, enhancement

#285 mgr server ip 설정 스크립트 추가
  shell/host/scvm_bootstrap.sh
Labels: bug

#286 Wall 서비스 배포 시 서비스 이름이 잘못되어 정상 실행되지 않는 문제 해결
  shell/host/scvm_bootstrap.sh
  src/features/wall-monitoring-wizard.js
Labels: bug

#290 Ceph insecure FALSE 설정 추가
  shell/host/scvm_bootstrap.sh
Labels: enhancement

#292 ccvm 배포후 5. 클러스터 구성 및 클라우드센터 가상머신 배포 단계에서 에러 발생
  python/vm/setup_pcs_cluster.py
Labels: bug

#293 ablestack-skydive 기능 추가
  main.html
  python/url/create_address.py
  src/features/cluster-config-prepare.js
  src/features/main.js
Labels: enhancement

#294 1. 스카이다이브 구성 소스 추가2. 주석 변경 및 console 에러 수정
  src/features/card-cloud-cluster-status.js
  src/features/main.js
  src/features/wall-monitoring-wizard.js
Labels: enhancement

#296 ABLESTACK 리본 표기 버그 수정
  main.html
  src/features/main.js
  src/features/wall-monitoring-wizard.js
Labels: bug

#298 HA 아키텍쳐 변경으로 인한 스크립트 및 코드 추가
  python/vm/setup_pcs_cluster.py
  shell/host/ccvm_bootstrap.sh
  shell/host/scvm_bootstrap.sh
Labels: enhancement
