Repository ablecloud-team/ablestack-cockpit-plugin, pull requests merged in 2022-10, with the labels that each got.

#361 호스트 추가 기능 개선
  main.html
  python/cluster/cluster_config.py
  python/cluster/cluster_hosts_setting.py
  python/glue/update_glue_config.py
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_ccvm_xml.py
  python/vm/setup_storage_vm.py
  src/common/wizard-common.js
  src/features/card-cloud-cluster-status.js
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.js
  src/features/main.js
  src/features/storage-vm-wizard.html
  src/features/storage-vm-wizard.js
Labels: enhancement

#363 scvm 배포시 disk 정보를 /dev/disk/by-path/ 를 참조하도록 개선
  python/disk/disk_action.py
  src/features/storage-vm-wizard.js
Labels: bug, enhancement

#364 scvm, ccvm qemu emulator 수정
  tools/xml-template/ccvm-xml-template-bios.xml
  tools/xml-template/ccvm-xml-template.xml
  tools/xml-template/scvm-xml-template-bios.xml
  tools/xml-template/scvm-xml-template.xml
Labels: bug, enhancement

#365 qemu 에뮬레이터 변경으로 인한 추가 수정 사항 적용 및 virtio-scsi 컨트롤러 기본 생성 적용
  tools/xml-template/ccvm-xml-template-bios.xml
  tools/xml-template/ccvm-xml-template.xml
  tools/xml-template/scvm-xml-template-bios.xml
  tools/xml-template/scvm-xml-template.xml
Labels: bug, enhancement

#366 디스크 컨트롤러 버그 수정 및 RBD 캐시 설정 및 CCVM 설정 변경
  shell/host/scvm_bootstrap.sh
  tools/xml-template/ccvm-xml-template.xml
  tools/xml-template/scvm-xml-template.xml
Labels: bug

#367 2022.10.18 Cerato 통합테스트 개선요구사항 반영
  python/cluster/cluster_config.py
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_ccvm_xml.py
  src/common/wizard-common.js
  src/features/card-cloud-cluster-status.js
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
  src/features/main.js
  src/features/storage-vm-status-update.js
  src/features/storage-vm-wizard.html
  src/features/storage-vm-wizard.js
  src/features/wall-monitoring-wizard.js
  tools/properties/cluster.json
Labels: bug, enhancement

#368 2022.10.21 통합테스트 수정사항 반영
  python/cluster/cluster_config.py
  python/cluster/cluster_hosts_setting.py
  python/glue/update_glue_config.py
  python/vm/create_ccvm_cloudinit.py
  python/vm/create_ccvm_xml.py
  python/vm/create_scvm_xml.py
  python/vm/host_ping_test.py
  python/vm/setup_pcs_cluster.py
  python/vm/setup_storage_vm.py
  shell/host/virsh_secret_key.sh
  src/common/wizard-common.js
  src/features/card-cloud-cluster-status.js
  src/features/cloud-vm-wizard.html
  src/features/cloud-vm-wizard.js
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
  src/features/main.js
  src/features/storage-vm-wizard.html
Labels: bug, enhancement
