Repository ablecloud-team/ablestack-cockpit-plugin, pull requests merged in 2022-11, with the labels that each got.

#369 [UI]전체 시스템 종료 문구 변경
  src/features/main.js
Labels: enhancement

#371 Glue crush ruleset 클래스 추가 위치 변경
  shell/host/ccvm_bootstrap.sh
  shell/host/scvm_bootstrap.sh
Labels: bug

#370 CCVM DNS undefined로 인식 되는 오류 수정
  python/host/virshlist.py
Labels: bug

#372 Crushmap 설정 버그 수정
  shell/host/ccvm_bootstrap.sh
Labels: bug, enhancement

#373 2022.11.14 통합테스트 수정사항 반영
  python/ccvm_snap/ccvm_snap_action.py
  src/features/cluster-config-prepare.html
  src/features/cluster-config-prepare.js
Labels: bug

#375 chrony 서버 시간 동기화 설정 파일 수정
  src/features/cluster-config-prepare.js
Labels: bug

#374 클러스터 구성 프로파일 입력 테이블 height 조절 (아래 입력란이 보이도록)
  src/features/cloud-vm-wizard.html
  src/features/cluster-config-prepare.html
  src/features/storage-vm-wizard.html
Labels: bug
