Repository ablecloud-team/ablestack-cockpit-plugin, pull requests merged in 2022-07, with the labels that each got.

#347 uefi변경에 대응 및 jenkins 빌드를 위한 버전관리
  python/host/virshlist.py
  python/vm/create_scvm_cloudinit.py
  python/vm/reset_cloud_center.py
  python/vm/reset_storage_center.py
  shell/host/scvm_bootstrap.sh
Labels: enhancement, Development

#348 Update scvm_bootstrap.sh
  shell/host/ccvm_bootstrap.sh
  shell/host/scvm_bootstrap.sh
  src/features/cloud-vm-wizard.js
Labels: bug

#349 ccvm 부트스트랩 변경
  .gitignore
  shell/host/ccvm_bootstrap.sh
Labels: bug

#352 클라우드센터 가상머신 mold 서비스 및 db 상태 체크가능하도록 기능개선
  main.html
  python/ccvm_service/ccvm_service_control.py
  python/host/virshlist.py
  src/features/card-cloud-cluster-status.js
  src/features/cloud-center-virtual-machine.js
Labels: enhancement
